language: cpp
dist: bionic
os: linux

matrix:
  include:

  - env:
      - TEST="Astyle Format"

    addons:
      apt:
        packages:
          - astyle

    script:
      - astyle --version
      - astyle --options=.astylerc 'multigeiger/*'
      - |
        if [[ -n $(git diff) ]]; then
          echo "astyle found the following issues - please fix them locally:"
          echo ""
          git diff
          exit -1
        fi

  - env:
      - TEST="PlatformIO build"

    language: python
    python: 3.6

    cache:
      directories:
        - "~/.platformio"

    install:
      - cp multigeiger/userdefines-example.h multigeiger/userdefines.h
      - cp platformio-example.ini platformio.ini
      - pip install -U platformio
      - platformio update

    script:
      - platformio run --environment geiger

